- hosts: all
  become: yes
  roles:
    - role: config_system
      tags: add_node

    - { role: config_lvm, when: "'replicaset_nodes' in hostvars[ansible_host]['group_names']", tags: add_node }

    - { role: config_shardrs, when: "'replicaset_nodes' in hostvars[ansible_host]['group_names']", tags: add_node }

    - { role: config_router, when: "'router_servers' in hostvars[ansible_host]['group_names']" }
