- hosts: teste
  tasks:
    - name: Teste
      debug:
        var: hostvars[item]['replica_set_name'] 
      with_items: "{{ groups['shard_servers'] }}"
  

# - hosts: router_servers
#   roles:
#     - config_router

# - hosts: all
#   any_errors_fatal: true
#   roles:
#     - config_system
#     # - { role: config_lvm, when: "'shard-servers' in group_names" }

# - hosts: replicaset-nodes
#   remote_user: root
#   become_user: root
#   become: yes
#   roles:
#     - config_lvm
#     - config_shardrs