- name: Create systemd configuration
  blockinfile:
    path: /etc/systemd/system/mongos.service
    block: |
      [Unit]
      Description=High-performance, schema-free document-oriented database
      After=syslog.target
      After=network.target

      [Service]
      User=mongodb
      Group=mongodb
      Type=forking
      RuntimeDirectory=mongodb
      RuntimeDirectoryMode=755
      PIDFile=/var/run/mongodb/mongos.pid
      ExecStart=/usr/bin/mongos --quiet \
          --config /etc/mongos.conf \
          --pidfilepath /var/run/mongodb/mongos.pid \
          --fork
      LimitFSIZE=infinity
      LimitCPU=infinity
      LimitAS=infinity
      LimitNOFILE=64000
      LimitNPROC=64000
      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    create: true

- name: "[ConfigSrv] Add Storage nodes in replicaset ConfigServer"
  set_fact:
    members: "{{ groups.config_servers|join(',') }}"
  with_items: "{{ groups.config_servers }}"

- name: Get replica set name
  set_fact:
    replicaset_name: "{{ hostvars[members.split(',')[0]]['replica_set_name'] }}"

# - name: Add a standalone mongod shard running on port 27018 of mongodb0.example.net
#   mongodb_shard:
#     shard: "{{ hostvars[item]['replica_set_name']  }}/{{ item }}"
#     state: present
#   with_items: "{{ groups['shard_servers'] }}"

- name: Create configurations file
  template:
    src: mongodb_router.conf.j2
    dest: /etc/mongos.conf

- name: Systemd enable Mongo QueryRouter
  systemd:
    name: mongos
    enabled: yes
    state: started
    daemon_reload: yes