- name: Install Mongodb and Dependencies
  yum:
    name: "{{ item }}"
    state: present
  loop:
    # - mongodb-org
    - epel-release
    - python-pip

- name: Python modules
  pip:
    name: "{{ item }}"
  loop:
    - setuptools
    - pymongo

#
# Anotações importantes para execução da task.
#  
# - Variavel shardings_config, suas propriedades estão em inventory/group_vars/shard-servers.yml

- name: Create configurations files
  template:
    src: mongodb_rs.conf.j2
    dest: /etc/mongod.conf

- name: Systemd enable cluster mongo
  systemd:
    name: mongod
    enabled: yes
    state: restarted
    daemon_reload: yes

#
# Shards Replicaser Config
#
- name: Include task list in play only if the condition is true
  include_tasks: "shardingrs.yml"
  when: "primary is defined and 'shard_servers' in hostvars[ansible_host]['group_names']"

#
# ConfigServer Replicaser Config
#
- name: Include task list in play only if the condition is true
  include_tasks: "shardingrs.yml"
  when: "primary is defined and 'config_servers' in hostvars[ansible_host]['group_names']"

