#
# Anotações importantes para execução da task.
#  
# - Variavel shardings_config, suas propriedades estão em inventory/group_vars/shard-servers.yml

- name: Copy Security Key File.
  copy:
    src: "{{ security_key }}"
    dest: /data/mongo_security.key
    owner: mongod
    group: mongod
    mode: '0600'


- name: Create configurations files
  template:
    src: mongodb_rs.conf.j2
    dest: /etc/mongod.conf

- name: Systemd enable cluster mongo
  systemd:
    name: mongod
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Waiting 30 seconds to MongoDB ready
  wait_for:
    timeout: 30

#
# Shards Replicaser Config
#
- name: Include task list in play only if the condition is true
  include_tasks: "shardingrs.yml"
  when: "primary is defined and 'shard_servers' in hostvars[ansible_host]['group_names']"

#
# ConfigServer Replicaser Config
#
- name: Include task list in play only if the condition is true
  include_tasks: "shardingrs.yml"
  when: "primary is defined and 'config_servers' in hostvars[ansible_host]['group_names']"

