# Variaveis de configuração das LVM's
disk_path: /dev/sdb
vg_name: vg_mongodb
pvs_name: /dev/sdb1
lv_name: lv_mongodb
mount_point: /data
file_system: xfs

# Tipo de sharding cluster: configsvr/shardsvr
cluster_role: shardsvr

# Porta do serviço do MongoDB, configsvr = 27019, shardsvr = 27017
replica_set_port: 27017

node_exporter: node_exporter-1.1.2.linux-amd64
mongodb_exporter: mongodb_exporter-0.20.4.linux-amd64